document.querySelectorAll('input[type="checkbox"]')
document.querySelectorAll('input[type="checkbox"]:not(:checked)')
document.querySelectorAll('[id|="message"]')
document.querySelectorAll('[id^="message-"]')
document.querySelectorAll('a[href$=".zip"]')
document.querySelectorAll('[data-action~="delete"]')
document.querySelectorAll('[data-action]:not([data-action~="delete"])')
document.querySelectorAll('#messages li:nth-child(2n)')
document.querySelectorAll('h3#widget-title + *')
document.querySelectorAll('h3#widget-title ~ a')
document.querySelectorAll('#messages li:last-child a')
